"""add_current_position_to_sessions

Revision ID: 39825c1edbc3
Revises: f8b88c1c42b5
Create Date: 2026-04-19 01:19:35.674245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '39825c1edbc3'
down_revision: Union[str, None] = 'f8b88c1c42b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('current_position', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'current_position')
    # ### end Alembic commands ###
