"""initial

Revision ID: f8b88c1c42b5
Revises: 
Create Date: 2026-04-19 00:41:31.641200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f8b88c1c42b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('margin_free', sa.Float(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('economic_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('actual', sa.Float(), nullable=True),
    sa.Column('forecast', sa.Float(), nullable=True),
    sa.Column('previous', sa.Float(), nullable=True),
    sa.Column('surprise', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_time', 'currency', 'name', name='uq_economic_event')
    )
    op.create_index(op.f('ix_economic_events_event_time'), 'economic_events', ['event_time'], unique=False)
    op.create_table('ohlc_m5',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'timestamp', 'source')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('presented_at', sa.DateTime(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('time_filter', sa.JSON(), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('spreads', sa.JSON(), nullable=False),
    sa.Column('timeframe_presets', sa.JSON(), nullable=False),
    sa.Column('tags_fixed', sa.JSON(), nullable=False),
    sa.Column('tags_custom', sa.JSON(), nullable=False),
    sa.Column('time_filter_presets', sa.JSON(), nullable=True),
    sa.Column('event_importance_threshold', sa.Integer(), nullable=False),
    sa.Column('event_currencies', sa.JSON(), nullable=True),
    sa.Column('event_shading_before_min', sa.Integer(), nullable=False),
    sa.Column('event_shading_after_min', sa.Integer(), nullable=False),
    sa.Column('risk_percent', sa.Float(), nullable=True),
    sa.Column('risk_amount', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trading_styles',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('primary_timeframe', sa.String(length=10), nullable=False),
    sa.Column('expected_hold_time', sa.String(length=50), nullable=False),
    sa.Column('expected_rr', sa.String(length=20), nullable=False),
    sa.Column('typical_sl_pips', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drawings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('add_reason', sa.Text(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('followup_ohlc', sa.JSON(), nullable=True),
    sa.Column('eval_tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_final_decisions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('has_entry', sa.Boolean(), nullable=False),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('considered_styles', sa.JSON(), nullable=True),
    sa.Column('followup_ohlc', sa.JSON(), nullable=True),
    sa.Column('eval_tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('trades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=5), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('sl', sa.Float(), nullable=False),
    sa.Column('tp', sa.Float(), nullable=True),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=20), nullable=True),
    sa.Column('pips_pnl', sa.Float(), nullable=True),
    sa.Column('amount_pnl', sa.Float(), nullable=True),
    sa.Column('lot', sa.Float(), nullable=True),
    sa.Column('mt5_order_id', sa.BigInteger(), nullable=True),
    sa.Column('style_id', sa.String(length=20), nullable=True),
    sa.Column('style_selection_reason', sa.Text(), nullable=True),
    sa.Column('followup_ohlc', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['trading_styles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_entry_time'), 'trades', ['entry_time'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_table('holding_memos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('trade_id', sa.String(length=36), nullable=False),
    sa.Column('environment', sa.Text(), nullable=True),
    sa.Column('market_view', sa.Text(), nullable=True),
    sa.Column('symbol_reason', sa.Text(), nullable=True),
    sa.Column('skipped_candidates', sa.Text(), nullable=True),
    sa.Column('event_recognition', sa.Text(), nullable=True),
    sa.Column('wave_count', sa.Text(), nullable=True),
    sa.Column('scenario_main', sa.Text(), nullable=True),
    sa.Column('scenario_alt1', sa.Text(), nullable=True),
    sa.Column('scenario_alt2', sa.Text(), nullable=True),
    sa.Column('entry_basis', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('exit_memo', sa.Text(), nullable=True),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('trade_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenarios')
    op.drop_table('holding_memos')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_entry_time'), table_name='trades')
    op.drop_table('trades')
    op.drop_table('session_final_decisions')
    op.drop_table('session_candidates')
    op.drop_table('drawings')
    op.drop_table('trading_styles')
    op.drop_table('settings')
    op.drop_table('sessions')
    op.drop_table('ohlc_m5')
    op.drop_index(op.f('ix_economic_events_event_time'), table_name='economic_events')
    op.drop_table('economic_events')
    op.drop_table('accounts')
    # ### end Alembic commands ###
